name: "🚨 Verificar se PR referencia uma issue"

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Verificando se PR referencia uma issue
        uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: '.*(close[sd]?|resolve[sd]?|fix(e[sd])?)\s+#\d+.*'
          helpMessage: "O título do PR deve referenciar uma issue, por exemplo: 'fixes #123' ou 'closes #456'."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}